@server=http://localhost:4004

# =================== READ ===================



### GET ALL MASTER DATA
GET {{server}}/app/MasterData
Content-Type: application/json

### GET ALL DATA HISTORY
GET {{server}}/app/DataHistory
Content-Type: application/json

### GET ALL TEST DATA
GET {{server}}/app/TestData
Content-Type: application/json

### GET ALL TEST DATA HISTORY
GET {{server}}/app/TestDataHistory
Content-Type: application/json

### GET ALL DATA TEMP STORAGE
GET {{server}}/app/DataTempStorage
Content-Type: application/json



# =================== CREATE ===================



### CREATE MASTER DATA
POST {{server}}/app/MasterData
Content-Type: application/json

{
    "title": "Title 1",
    "type": "B"
}

### CREATE TEST DATA
POST {{server}}/app/TestData
Content-Type: application/json

{
    "title": "Title 1",
    "type": "A"
}


# =================== UPDATE ===================


### UPDATE MASTER DATA 1
PATCH  {{server}}/app/MasterData/0e0e350d-7015-4383-a8d7-679285a04f75
Content-Type: application/json

{
    "title": "Title 6",
    "type": "B"
}

### UPDATE MASTER DATA 2
PATCH  {{server}}/app/MasterData/d92509f1-5a6f-4700-9bab-9c37c6eb56fd
Content-Type: application/json

{
    "title": "Title 4",
    "type": "B"
}

### UPDATE TEST DATA 1
PATCH  {{server}}/app/TestData/caabf45b-e0e9-4f14-8d42-2ff811c9a27e
Content-Type: application/json

{
    "title": "Title 2",
    "type": "B"
}


# =================== DELETE ===================



### DELETE TEST DATA 1
DELETE   {{server}}/app/TestData/765897c6-a6b2-4431-9a42-818397b51867



# =================== ACTIONS ===================


###
POST {{server}}/app/updateData
Content-Type: application/json

{}