@server=http://localhost:4004



# =================== READ ===================



### GET ALL DATA
GET {{server}}/app/Data
Content-Type: application/json

### GET ALL DATA HISTORY
GET {{server}}/app/DataHistory
Content-Type: application/json

### GET ALL DATA TEMP STORAGE
GET {{server}}/app/DataTempStorage
Content-Type: application/json

### GET Change log
GET {{server}}/app/DataChangeView
Content-Type: application/json

### GET DataWithStatuses
GET {{server}}/app/DataWithStatuses
Content-Type: application/json

### GET DataStatuses
GET {{server}}/app/DataStatuses
Content-Type: application/json



# =================== CREATE ===================



### CREATE DATA
POST {{server}}/app/Data
Content-Type: application/json

{
    "title": "Title 1",
    "type": "B"
}



# =================== UPDATE ===================



### UPDATE DATA 1
PATCH  {{server}}/app/Data/8dccae16-8d8b-49cb-acb8-649789bdb9de
Content-Type: application/json

{
    "title": "Title 8",
    "type": "A"
}

### UPDATE DATA 2
PATCH  {{server}}/app/Data/943c6963-9b30-42ea-87df-04f85efff5c5
Content-Type: application/json

{
    "title": "Title 2",
    "type": "B"
}


### UPDATE DATA STATUS
PATCH  {{server}}/app/DataStatuses/84c2572e-be31-4e75-8a3f-d2d2d6e395d7
Content-Type: application/json

{
    "status_code": "TBU"
}



# =================== DELETE ===================



### DELETE DATA 1
DELETE   {{server}}/app/Data/b5318e80-3ccd-4f64-9ae9-039cca712d66



# =================== ACTIONS ===================


###
POST {{server}}/app/updateData
Content-Type: application/json

{}